### PR TITLE
fixed Onboarding fails on system_registry with "Unable to find ca-sig…

### LINKED ISSUE #229: Onboarding fails on system_registry with "Unable to find ca-sign"
system_registry fails to query ca-sign from orchestration service. It works on device_registry because device_registry fetches the uri through the URI crawler task (through service_registry).

### PR DESCRIPTION
**Pull request by mzsilak**
Ready for review #229

### CODE REVIEW

File: core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java [hunk 1]
```diff
@@ -88,6 +90,17 @@ public boolean pingService(final ServiceSecurityType securityType, final SystemR
         return pingService(echoUri);
     }
 
+    public UriComponents findUri(final CoreSystemService service) throws DriverException {
+        try {
+            return findUriByOrchestrator(service);
+        } catch (final Exception e) {
+            // silently ignored
```
Comment (rbocsi) [inline core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java]: please don't do this. At the very least, log the exception

File: core-common/src/main/java/eu/arrowhead/common/drivers/EventDriver.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    // members
+    private final ObjectMapper mapper = new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
+    private final Logger logger = LogManager.getLogger(EventDriver.class);
+
+    @Autowired
+    public EventDriver(final DriverUtilities driverUtilities, final HttpService httpService) {
+        super(driverUtilities, httpService);
+    }
+
+    public void publish(final EventPublishRequestDTO request) throws DriverUtilities.DriverException {
```
Comment (rbocsi) [inline core-common/src/main/java/eu/arrowhead/common/drivers/EventDriver.java:38]: maybe you should check inputs in every public method before using them
